# Generated by Django 5.0.4 on 2024-05-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_logindata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginData',
        ),
    ]
