# Generated by Django 5.0.4 on 2024-05-13 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
