# Generated by Django 5.1.1 on 2025-01-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_habit_user_task_user_goal_task_goal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
